### PR TITLE
Added support for autoscrolling

### PR DESCRIPTION
**Pull request by agnjunio**
Using dnd-autoscroll="true" and opitional variables:
- dnd-autoscroll-sensitivity="int" set the pixels in the beggining and in the end of the list that will trigger the scrolling
- dnd-autoscroll-speed="int" will scroll N pixels based in this argument

### CODE REVIEW

**Comment by marceljuenemann** [comment]
See #295, I think this should be in it's own directive since it doesn't need to interact with the existing dnd-list code much

**Comment by mcblum** [comment]
@marceljuenemann It would be awesome to get this merged with master! Once you have elements that are bigger dragging and dropping over scroll becomes a huge pain!

**Comment by aidenZhou** [comment]
@mcblum , does it work for you? I just tried to use this. It seems it is not working. I just updated the following codes. Am I doing it right?
<li ng-repeat="item in list"
        dnd-draggable="item"
        dnd-autoscroll="true"
        dnd-moved="list.splice($index, 1)"
        dnd-effect-allowed="move"
        dnd-selected="models.selected = item"
        ng-class="{'selected': models.selected === item}"
        >
        {{item.label}}
    </li>

**Comment by agnjunio** [comment]
@aidenZhou Just guessing here, but since this merge request I made was based on the current master at the time (Jun 2016) and since it's been over a year now, maybe you're using new features that came along and that aren't part of this fork.

You have 2 options here:
1) Fork the current updated master and re-implement my changes or
2) Upvote this request to let the owners know we need this feature and hopefully merge this one

When I have some time to spare, I will rebase my branch as well.

**Comment by agnjunio** [comment]
Ok, try pulling the latest changes (it may conflict, so consider re-cloning if you aren't experienced with git). I just rebase with the latest changes so it won't conflict anymore.

**Comment by jheimbouch** [comment]
+1

**Comment by AlexanderArmua** [comment]
+1

**Pull request closed without merging**
