### PR TITLE
Add basic debouncing to dragging(100 ms).

### PR DESCRIPTION
**Pull request by gkohen**
Github issue# 139: Dragging is overwhelming callbacks queue on the JS VM.

### CODE REVIEW

**Comment by bernyfox** [comment]
+1

**Comment by jaymanned** [comment]
+1

**Comment by mattgoldspink** [comment]
In case people need even more performance improvements I've got a branch here which includes further optimizations to allow Chrome to optimize functions (re-assigning to event argument means Chrome can't optimize). It skips the IE logic in Chrome, Firefox and Safari (not the cleanest solution but gives huge performance gains for us in that browser). Heavily optimize isMouseInFirstHalf by removing as many DOM offset touches as possible - also added an extra data-dnd-height attribute so that the offsetHeight can be skipped if you know that element heights will always be the same. In addition it skips adding the placeholder twice (avoid unnecessary DOM writes). 

We had clients with a list over 500 elements. These all helped us bring the drag/drop to a super smooth animation rate in chrome and firefox for us.

**Comment by marceljuenemann** [comment]
v2 has a new placeholder positioning algorithm that should have similar changes. About the debouncing I'm not convinced it is needed, as the HTML5 standard says browsers should call the event handlers only a few times per second. But feel free to reopen if you have some hard data that some browsers call these more often.

**Comment by mattgoldspink** [comment]
Hi @marceljuenemann - firstly thank you for your awesome work on this library. We tried pretty much every other drag and drop angular library and this was by far the best. We use it in one of our products heavily so I'll give the v2 version a shot with some of our larger data sets and let you know how it compares.

Thanks again for all the hard work you put in on this.

**Pull request closed without merging**
