### PR TITLE
Added autoScroll abilities

### PR DESCRIPTION
**Pull request by jtheoof**
Hi @marceljuenemann,

I gave a first shot at auto scrolling supported natively in this really cool library you developed. As stated in the `README.md` it will handle auto scrolling if the element drag over approaches the edges of its list container or the window. It's also "smart enough" to handle `horizontal` and vertical list.

Hope it finds its way in `master`.

### CODE REVIEW

**Comment by marceljuenemann** [comment]
Interesting, thanks for putting in the work!

I haven't made up my mind yet whether this should be part of the core directive, but on the other hand it looks simple enough and is optional...

One thing to fix is definitely not to rely on dragover events for timing. Different browsers will trigger this event in different intervals, so the scroll speed would be different depending on the browser (possibly way too fast)

**Comment by jtheoof** [comment]
Yes I agree it's not the cleanest way to do it. 

My first approach was to use the `dragstart` and `dragend` event, adding a `mousemove` listener but the problem that I found was that those two events are related to the object being dragged, and not the list itself.

I would appreciate your guidance in that matter.

**Comment by jtheoof** [comment]
So I've tried to move the auto scroll out of the drag over in a different branch. You can see the [diff here](https://github.com/marceljuenemann/angular-drag-and-drop-lists/compare/master...jtheoof:auto-scroll-without-dragover?expand=1).

The problem now is that the `mousemove` event handler is not being called when dragging an element over. Only `dragover` is fired.

I am gonna try to see if I find other ways.

**Comment by jtheoof** [comment]
@marceljuenemann I think I've found a more elegant solution. Wrapping the scrolling inside an `$interval`. Let me know what you think.

**Comment by jtheoof** [comment]
@marceljuenemann I'd love to get this feature merge. I would gladly work on any feedback you might have. Adding tests... I think the community would really benefit from having scrolling handled directly in the lib.

**Comment by marceljuenemann** [comment]
Cool, your code looks good from my first glance over it, nice work!

I'm still wondering though: Except for the horizontal attribute you're not really interacting with the other dnd-list code. Therefore, I'm thinking this should be it's own directive, that way it could be used for all HTML5 drag & drop code, not just for the dnd-list directive.

I'd even consider just having an angular module that just listens on dragstart/dragend events on $document, since all events are propagated. What do you think?

**Comment by mcblum** [comment]
Would really love to see this in master!

**Comment by jtheoof** [comment]
I'll try to handle @marceljuenemann comments sometime over the next few days.

**Comment by mcblum** [comment]
That's awesome, @jtheoof. Thank you for your work on this -- going to be a great addition to this library!

**Comment by jtheoof** [comment]
I am some time to rework on that pull request. I'll review @marceljuenemann comment and see how I can implement the `module` part of your comment.

**Comment by jtheoof** [comment]
There are a few `event.stopPropagation();` in the code that will prevent the event from being propagated into `$document`. I am not sure that I can simply remove them without breaking code for devs using this lib.


```
$ git grep -B5  -n 'event.stopPropagation'
angular-drag-and-drop-lists.js-113-        }
angular-drag-and-drop-lists.js-114-
angular-drag-and-drop-lists.js-115-        // Invoke callback
angular-drag-and-drop-lists.js-116-        $parse(attr.dndDragstart)(scope, {event: event});
angular-drag-and-drop-lists.js-117-
angular-drag-and-drop-lists.js:118:        event.stopPropagation();
--
angular-drag-and-drop-lists.js-148-
angular-drag-and-drop-lists.js-149-        // Clean up
angular-drag-and-drop-lists.js-150-        element.removeClass("dndDragging");
angular-drag-and-drop-lists.js-151-        $timeout(function() { element.removeClass("dndDraggingSource"); }, 0);
angular-drag-and-drop-lists.js-152-        dndDragTypeWorkaround.isDragging = false;
angular-drag-and-drop-lists.js:153:        event.stopPropagation();
--
angular-drag-and-drop-lists.js-164-        scope.$apply(function() {
angular-drag-and-drop-lists.js-165-          $parse(attr.dndSelected)(scope, {event: event});
angular-drag-and-drop-lists.js-166-        });
angular-drag-and-drop-lists.js-167-
angular-drag-and-drop-lists.js-168-        // Prevent triggering dndSelected in parent elements.
angular-drag-and-drop-lists.js:169:        event.stopPropagation();
--
angular-drag-and-drop-lists.js-355-          return stopDragover();
angular-drag-and-drop-lists.js-356-        }
angular-drag-and-drop-lists.js-357-
angular-drag-and-drop-lists.js-358-        element.addClass("dndDragover");
angular-drag-and-drop-lists.js-359-        event.preventDefault();
angular-drag-and-drop-lists.js:360:        event.stopPropagation();
--
angular-drag-and-drop-lists.js-415-          dndDropEffectWorkaround.dropEffect = event.dataTransfer.dropEffect;
angular-drag-and-drop-lists.js-416-        }
angular-drag-and-drop-lists.js-417-
angular-drag-and-drop-lists.js-418-        // Clean up
angular-drag-and-drop-lists.js-419-        stopDragover();
angular-drag-and-drop-lists.js:420:        event.stopPropagation();
--
angular-drag-and-drop-lists.js-610-          // If a child element already reacted to dragstart and set a dataTransfer object, we will
angular-drag-and-drop-lists.js-611-          // allow that. For example, this is the case for user selections inside of input elements.
angular-drag-and-drop-lists.js-612-          if (!(event.dataTransfer.types && event.dataTransfer.types.length)) {
angular-drag-and-drop-lists.js-613-            event.preventDefault();
angular-drag-and-drop-lists.js-614-          }
angular-drag-and-drop-lists.js:615:          event.stopPropagation();
--
angular-drag-and-drop-lists.js-621-       * would be removed.
angular-drag-and-drop-lists.js-622-       */
angular-drag-and-drop-lists.js-623-      element.on('dragend', function(event) {
angular-drag-and-drop-lists.js-624-        event = event.originalEvent || event;
angular-drag-and-drop-lists.js-625-        if (!event._dndHandle) {
angular-drag-and-drop-lists.js:626:          event.stopPropagation();
```

**Comment by jtheoof** [comment]
I have traced the `event.stopPropagation` in `dragstart` and `dragend` back to [30c7327087d64c16eae21fb50729bfe219ecb354](https://github.com/marceljuenemann/angular-drag-and-drop-lists/commit/30c7327087d64c16eae21fb50729bfe219ecb354) which is the second commit in the repo :)

**Comment by jtheoof** [comment]
OK I've reworked it and add a `dndAutoScroll` module. I like it this way as well but we've lost something that present in previous changeset. Previously, we could also auto scroll drop zones that were set with `max-width` and `overflow: auto;`. With this changeset, we've lost this ability. There might ways to circumvent this by using `document.elementFromPoint` during `drag` event but it will not necessarily return the element that is overflown.

Also the autoScrollSpeed is hard coded, but that could easily be fixed by adding a `config` object to the module.

I've added a new route in demo: `autoscroll`. Please have a look at it (especially the *Narrow* list which highlights the issue I just mentioned).

Still a work in progress but in good shape in my opinion.

**Comment by ifeltsweet** [comment]
+1, need this feature.

**Comment by mrgcohen** [comment]
+1

**Comment by marceljuenemann** [comment]
Hey, thanks for the PR! Some problems I see with the current approach:

- Propagating dragstart and dragend events will lead to big problems in nested lists
- It's not uncommon to have single page applications where you only scroll inside an element which is not the window
- The approach won't work for dnd-external-sources.

Ideally there would be an easy solution to this that just listens on all `drag` events, and doesn't require any jQuery or angular, so that it's extremely reusable between libraries. I'm thinking something in [this direction](http://stackoverflow.com/a/29038309/1620264), although that one does also not work for non-window DOM elements.

**Comment by ha0x7c7** [comment]
any update on this?

**Comment by goldins** [comment]
Just tested this locally and it's exactly what I need. Would like to see this merged as well.

**Comment by ha0x7c7** [comment]
@goldins it might be silly to ask, but how can I get this version?

**Comment by goldins** [comment]
I pretty much just copied and pasted the code for development to test. But for a more permanent (though not perfect) solution, you can include this in your bower.json file:
`"angular-drag-and-drop-lists": "git@github.com:jtheoof/angular-drag-and-drop-lists.git#auto-scroll"` to grab this specific branch from @jtheoof. Make sure to use the non-minified file (since the .min.js changes are not in this PR). Note that this is a very bad idea for production since it's not versioned and you may accidentally pick up unwanted changes.

**Comment by aidenZhou** [comment]
@goldins , I just tested this code, it is not working for me. I just need to replace my angular-drag-and-drop-lists.js with jtheoof's repo, right? I am using this on a page which is injected using ui-view. Is this the reason that the codes are not working for me?
By the way, I just check the simple list demo page. It seems the demo has auto scroll feature. If I drag the item to the bottom of the page, the page will scroll down a little bit automatically.

**Comment by mcblum** [comment]
Does anyone know the status of this? This would be a really great addition to the package.

**Comment by ha0x7c7** [comment]
I switched to angular-dragdrop which is a wrapper around jquery-ui, our application relied heavily on scroll capabilities which made us to switch from this library.

**Comment by jtheoof** [comment]
The work / effort I put to try to have a proper fix that satisfies the needs without breaking anything is quite important. I did not make time to try @marceljuenemann recommendation but I'm hoping to resubmit a new version at some point.

**Pull request closed without merging**
