### PR TITLE
Support for drag handles via dnd-handle directive

### PR DESCRIPTION
**Pull request by cmlenz**
Add support for drag handles using a new `dnd-handle` directive. See #31 and #35.

### CODE REVIEW

**Comment by justinklemm** [comment]
:+1:

**Comment by maelvis** [comment]
I just see the commit but nothing in the downloadable demo. 

When will the commit be merged ???

**Comment by andrieski** [comment]
Hi, I'd like to test out and use these draggable handles. How can I merge this pull request on my local copy? I tried 

```
$ git clone https://github.com/marceljuenemann/angular-drag-and-drop-lists.git
-b handle-support /my_clone
```

as per the instructions at http://stackoverflow.com/questions/14947789/github-clone-from-pull-request
but the error is: remote branch "handle-support" hasn't been found?

**Comment by troygilbert** [comment]
This works great for me, would love to see this merged into the mainline.

**Comment by michaelbromley** [comment]
Just a note to say I used this PR and it works well for me. A sorely missing feature from an otherwise excellent project! Well done to the original author and to @cmlenz for this enhancement.

**Comment by ajmajma** [comment]
!bump to merge this PR in.

**Comment by dovy** [comment]
Bump to merge.

**Comment by none-da** [comment]
:+1:

**Comment by onemenny** [comment]
why is this not merged? there are many pull req with various solution to this problem - so pull one and close the others

**Comment by marceljuenemann** [comment]
@onemenny: For me quality is more important than feature richness, so I won't just "pull one and close the others", but I want to spend time on it to find the best solution and test it on every browser & OS. I coded this directive on a weekend and never intended to spend much time on it, but I'm very happy to see that it is so useful to others. I hope I'll get out a new release in August, but that literally depends on the weather and if I find a free weekend that I want to spend on this. Feel free to fork and maintain it more actively than I do.

**Comment by onemenny** [comment]
@marceljuenemann Thank you for making this clear. before your comment it seemed that no one was looking into it. I realy hope that you'll get to it in August and i understand what is OSS project... 

currently i'm using https://github.com/SeedJobs/angular-drag-and-drop-lists.git solution which solves the handle issue and the click propagation issue as well, it will go into production next month and i can update the status if you like about this branch stability or bugs in ever green browsers...

**Comment by marceljuenemann** [comment]
New release is out now

**Comment by onemenny** [comment]
Thank you for this release, 
the nodrag demo does not seem to work on FF. in the changelog i see that it should work. am i missing something?

**Pull request closed without merging**
